import type { Metadata } from 'next'

import { montserrat } from '@/styles/fonts/fonts'

import '@/styles/reset.scss'
import '@/styles/variables.scss'
import '@/styles/globals.scss'

export const metadata: Metadata = {
	title: 'City Agency',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>{children}</body>
		</html>
	)
}
