import Link from 'next/link'
import Image from 'next/image'
import { Metadata } from 'next'

import notFoundIcon from '@/assets/images/404-not-found.svg'

import styles from './not-found.module.scss'
import btnStyles from '@/components/Button/Button.module.scss'
import Header from '@/components/Header/Header'
import Menu from '@/components/Menu/Menu'

import { montserrat } from '@/styles/fonts/fonts'

export const metadata: Metadata = {
	title: 'Page not found | City Agency',
	description: 'Generated by create next app',
}

export default function NotFound() {
	return (
		<main className={montserrat.className}>
			<div className={styles.container}>
				<div className={styles.wrapperLogoBox}>
					<Header page='Not-Found'></Header>
				</div>

				<div className={styles.wrapperNotFound}>
					<Image
						className={styles.notFoundIcon}
						src={notFoundIcon}
						alt='not-found-icon'
						width={617}
						height={213}
						priority
					/>
					<Link href='/' className={`${btnStyles.primaryBtn} ${styles.linkToMain}`}>
						Return to Main
					</Link>
				</div>
				<Menu />
			</div>
		</main>
	)
}
