import type { Metadata } from 'next'

import Sidebar from './components/sidebar'
import Header from './components/header'

import { nunitoSans } from '@/styles/fonts/fonts'

import styles from './page.module.scss'

export const metadata: Metadata = {
	title: 'Dashboard | City Agency',
	description: 'Generated by create next app',
}

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className={`${styles.wrapper} ${nunitoSans.className}`}>
			<Sidebar />
			<div className={styles.content}>
				<Header />
				<div className={styles.contentInner}>
					{children}
				</div>
			</div>
		</div>
	)
}
